### ISSUE TITLE
Nginx Docker - crt and key files

### ISSUE THREAD

**Issue by houshuang** [uts-cic/acawriter#70]
The Docker file for Nginx wants to copy a .crt and a .key file that is not part of the repo, and there are no instructions in the README for generating these files.

![image](https://user-images.githubusercontent.com/61575/131968156-473665c7-f4e4-4c8d-8e5d-d8ab7a8a9640.png)

**Comment by lijianw2** [comment]
I generated my own key and certificates using these: 
openssl genrsa -out acawriter.key
openssl req -new -key acawriter.key -out acawriter.csr
openssl x509 -req -days 365 -in acawriter.csr -signkey acawriter.key -out acawriter.crt

**Comment by genieza** [comment]
can you explain how to do it?

**Comment by andreyinkin** [comment]
This error is fixed - SSL cert is not required when run locally, and is only required for our production install. It no longer fails when it cannot find these files.
